#!/usr/bin/env python 

from tempfile import mkstemp, mkdtemp
from shutil import rmtree, move
import sys
import os
from subprocess import call


filename = sys.argv[1]
if not filename.endswith(".tex"):
	filename += ".tex"
f = open(filename, "w")

try:
	f.write(
	r'''
	\documentclass[a4paper]{minimal}
	\usepackage[margin=0.5in,landscape]{geometry}
	\usepackage[utf8]{inputenc}
	\usepackage{lmodern}
	\usepackage{grffile}
	\usepackage[pdftex]{graphicx}
	\usepackage{moresize}
	\begin{document}
	''')
	for i in sys.argv[2:]:
		b = os.path.splitext(os.path.basename(i))[0]
		d = os.path.dirname(i)
		f.write(r'\centering {\HUGE\verb+%s+} \newline\includegraphics[width=\textwidth,height=0.9\textheight,keepaspectratio]{%s}\newline\verb+%s+\newpage'%(b, i, d))
		f.write("\n")
	
	f.write(
	r"""
	\end{document}
	""")

	f.close()
	call(['pdflatex', '-interaction=batchmode', '-halt-on-error', '-shell-escape', filename])
finally:
	pass	