#!/bin/bash

if [ $# = 0 ]; then
	echo "qsubmit <COUNT> <EXECUTABLE> [<PARAMETERS>]"
	echo ""
	echo "e.g."
	echo "> qsubmit 10 sleep $\(Process\)"
	echo ""

	exit 1
fi

queue=$1
shift
exe=$1
shift
args=$@
condor_submit <<EOF
Executable     = $exe
arguments      = $args
Error   = \$(Cluster)-\$(Process)-error.txt
Output  = \$(Cluster)-\$(Process)-output.txt
Log     = \$(Cluster)-log.txt
Notification = Error
kill_sig = SIGTERM
+IsSuspensionJob = false
getenv        = True
Queue $queue
EOF
