#!/usr/bin/env python


import sys, yaml, json

fin = sys.stdin
if len(sys.argv) > 1 and sys.argv[1] != '-':
  fin = open(sys.argv[1])

fout = sys.stdout
if len(sys.argv) > 2 and sys.argv[2] != '-':
  fout = open(sys.argv[2], 'w')

json.dump(yaml.load(fin), fout, indent=2)
